lists/urls.py
from django.conf.urls import include, url
from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
]

superlists/urls.py
from django.conf.urls import include, url
from lists import views as list_views
from lists import urls as list_urls
from blog import views as blog_views

urlpatterns = [
    url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include(list_urls)),
    url(r'^blog/', blog_views.blog_page, name='blog'),
]

blog/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
	title = models.CharField(max_length=100, unique=True)
	slug = models.SlugField(max_length=100, unique=True)
	body = models.TextField()
	posted = models.DateField(db_index=True, auto_now_add=True)
	category = models.ForeignKey('blog.Category')

class Category(models.Model):
	title = models.CharField(max_length=100, db_index=True)
	slug = models.SlugField(max_length=100, db_index=True)

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class List(models.Model):
	def get_absolute_url(self):
		return reverse('view_list', args=[self.id])
	
class Item(models.Model):
	text = models.TextField(default='')
	list = models.ForeignKey(List, default=None)

blog/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse

# Create your views here.

def blog_page(request):
	return render(request, 'blog.html',)

lists/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import redirect, render
from django.http import HttpResponse
from lists.models import Item, List

# Create your views here.
def home_page(request):
	item_counter = 0
	the_comment = ""
	if item_counter == 0:
		the_comment = 'yey, waktunya berlibur'
	elif item_counter < 5:
		the_comment = 'sibuk tapi santai'
	else:
		the_comment = 'oh tidak'
	return render(request, 'home.html', {'comment': the_comment},)

def view_list(request, list_id):
	list_ = List.objects.get(id=list_id)
	item_counter = Item.objects.filter(list=list_).count()
	error = None

	the_comment = ""
	if item_counter == 0:
		the_comment = 'yey, waktunya berlibur'
	elif item_counter < 5:
		the_comment = 'sibuk tapi santai'
	else:
		the_comment = 'oh tidak'

	if request.method == 'POST':
		try:
			item = Item(text=request.POST['item_text'], list=list_)
			item.full_clean()
			item.save()
			return redirect(list_)
		except ValidationError:
			error = "You can't have an empty list item"
	return render(request, 'list.html', {'list': list_, 'comment': the_comment, 'error': error})

def new_list(request):
	list_ = List.objects.create()
	item = Item.objects.create(text=request.POST['item_text'], list=list_)
	try:
		item.full_clean()
		item.save()
	except ValidationError:
		list_.delete()
		error = "You can't have an empty list item"
		return render(request, 'home.html', {"error": error})
	return redirect(list_)

def blog_page(request):
	return render(request, 'blog.html',)

blog/templates/blog.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>My Personal Blog</title>
		<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link href="/static/base.css" rel="stylesheet">
	</head>
	<body>
		<div class="container">

			<div class="row">
				<div class="col-md-6 col-md-offset-3 jumbotron" id="my_name">
					<div class="text-center">
						<h2>Welcome to my Blog!</h2>
						<h4>My name is Dhika Ayu Agustin Cahyani</h4>
						<p>Here you can find little story about me.</p>
					</div>
				</div>
			</div>

			<div class="row">
				<div id="posts" class="col-md-6 col-md-offset-3">
					<h3>This is my first post</h3>
					<p>Middterm exam is starting in 4 days.
					I can't deny that I am panicking. 
					I am hungry.
					</p>
				</div>
			</div>
		</div>
		
	</body>
</html>

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>To-Do lists</title>
		<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link href="/static/base.css" rel="stylesheet">
	</head>
	<body>
		<div class="container">

			<div class="row">
				<div class="col-md-6 col-md-offset-3 jumbotron" id="id_div_input">
					<div class="text-center">
						<h1>{% block header_text %}{% endblock %}</h1>
						<form method="POST" action="{% block form_action %}{% endblock %}">
							<input name="item_text" id="id_new_item" class="form-control input-lg" placeholder="Enter a to-do item" />
							{% csrf_token %}
							{% if error %}
								<div class="form-group has-error">
										<span class="help-block">{{ error }}</span>
								</div>
							{% endif %}
						</form>
					</div>
				</div>
			</div>

			<div class="row">
				<div id="id_div_table" class="col-md-6 col-md-offset-3">
					{% block table %}
					<p>Your to-do list goes here.<p1>
					{% endblock %}
					<h1>Comments:</h1>
					<p name="comment_text" id="id_comment">{{ comment }}</p>
				</div>
			</div>

			<div class="row">
				<div id="id_blog_address" class="col-md-6 col-md-offset-3">
					<p>Please visit my blog at this <a href=/blog/>address</a></p>
				<div>
			</div>

		</div>
		
	</body>
</html>

lists/templates/blog.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>My Personal Blog</title>
		<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link href="/static/blog.css" rel="stylesheet">
	</head>
	<body>
		<div class="container">

			<div class="row">
				<div class="col-md-6 col-md-offset-3 jumbotron" id="my_name">
					<div class="text-center">
						<h2>Welcome to my Blog!</h2>
						<h4>My name is Dhika Ayu Agustin Cahyani</h4>
						<p>Here you can find little story about me.</p>
					</div>
				</div>
			</div>

			<div class="row">
				<div id="posts" class="col-md-6 col-md-offset-3">
					<h3>This is my first post</h3>
					<p>Middterm exam is starting in 4 days.
					I can't deny that I am panicking. 
					I am hungry.
					</p>
				</div>
			</div>

			<div class="row">
				<div id="posts2" class="col-md-6 col-md-offset-3">
					<h3>This is my second post</h3>
					<p>
					Boom, this is my second post.
					</p>
				</div>
			</div>
		</div>
		
	</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
	<table id="id_list_table" class="table">
		{% for item in list.item_set.all %}
			<tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
		{% endfor %}
	</table>
{% endblock %}